## Midterm
### You have 60 minutes to solve 4 questions given below. 

### Do not change the code that has been provided to you. You can add code but do not change/remove any components provided by us.

In [3]:
import numpy as np
import pandas as pd

**Question 1:** Complete the function `question1` based on the instructions given below. <br>

### Given a numpy array, return the maximum element from each row in a list

x=
[[4 8 3]<br>
  [2 9 7]<br>
  [0 2 7]]<br>

question1(x) = [8,9,7]

In [9]:
def question1(arr):
    '''
    1 local test case : 5 points
    1 hidden test case : 5 points
    '''
    return [max(row) for row in arr]

def q1e(arr):
    '''
    1 local test case : 5 points
    1 hidden test case : 5 points
    '''
    return np.max(arr, axis=1).tolist()

def q1ea(arr):
    return [max(arr[:,i]) for i in range(len(arr[0]))]

def q1eb(arr):
    return np.max(arr, axis=0).tolist()

In [10]:
# question1(np.array([[1,2,3],[4,5,6],[7,8,9]]))  # Example usage
q1eb(np.array([[1,2,3],[4,5,6],[7,8,9]]))

[7, 8, 9]

**Question 2:** Complete the function `question2` based on the instructions given below. <br>

### Given an integer argument return factorial of the value. Hint: Use recursion.

Note: The factorial function says to multiply all whole numbers from our chosen number down to 1.

Examples:

question4(4) = 4 × 3 × 2 × 1 = 24


In [7]:
def question2(num):
    '''
    1 local test case : 5 points
    1 hidden test case : 5 points
    '''
    if num <= 1:
        return num
    return num * question2(num - 1)

In [8]:
question2(4)

24

**Question 3:** Complete the function `question3` based on the instructions given below.<br>

### Apply the following instructions (in order) to an input two dimensional numpy array with 0s and 1s and return the output


**\<Operations to perform\>**

<ol>
    <li> Reverse the odd rows.
    <li> Once the odd rows are reversed, replace the first element of every column according to the following logic : If the column contains even number of 1's replace the first element of that column with a 0. If a column has odd number of 1's replace the first element of that column with a 1.<br>
        Ex: column = [1, 0, 0, 1]<br>
        numberOf1s(column) = 2; even, so we replace the first element of the column with a 0<br>
        column = [0, 0, 0, 1]
    <li> Replace the 0's in each column by the mean of the array.<br>
        Ex. col = [1, 0, 0, 1]<br>
        array_mean = 0.5; here the array_mean is the mean of the entire array.<br>
        output = [1, 0.5, 0.5, 1]
    <li> Multiply all the elements of the array with 255
    <li> Return the transpose of the array
    
</ol>

In [36]:
arr2 = np.array([[1,0,0], [1,1,0], [0,0,0], [1,0,1]])
np.where(arr2==0, 122, arr2)
arr2

array([[1, 0, 0],
       [1, 1, 0],
       [0, 0, 0],
       [1, 0, 1]])

In [43]:
np.mean(arr2, axis=0)

array([0.75, 0.25, 0.25])

In [ ]:
def question3(arr):
    '''
    1 local test case : 15 points
    1 hidden test case : 25 points
    '''
    arr = arr.copy().astype(float)
    nrows = arr.shape[0]
    ncols = arr.shape[1]
    #1 reverse odd rows
    for i in range(nrows):
        if (i+1) % 2 == 1:
            arr[i] = arr[i][::-1]
    print(arr)

    #2 set first row based on odd/even 1s in each col
    for i in range(ncols):
        col = arr[:,i]
        if col.sum() % 2 == 0:
            arr[0, i] = 0
        else:
            arr[0, i] = 1
    print(arr)
    
    #3 set each 0 to mean of its column
    for i in range(ncols):
        col = arr[:,i]
        mean = np.mean(col)
        for j in range(nrows):
            if arr[j, i] == 0:
                arr[j, i] = mean
    print(arr)
    
    # 4/5 scale by 255 and tranpsose
    return (arr * 255).T

In [41]:
question3(arr2)

[[0. 0. 1.]
 [1. 1. 0.]
 [0. 0. 0.]
 [1. 0. 1.]]
[[0. 1. 0.]
 [1. 1. 0.]
 [0. 0. 0.]
 [1. 0. 1.]]
[[0.5  1.   0.25]
 [1.   1.   0.25]
 [0.5  0.5  0.25]
 [1.   0.5  1.  ]]


array([[127.5 , 255.  , 127.5 , 255.  ],
       [255.  , 255.  , 127.5 , 127.5 ],
       [ 63.75,  63.75,  63.75, 255.  ]])

**Question 4:** Complete the function `question4` based on the instructions given below.<br>

### Convert a given number to its Roman counter part in a pandas DataFrame.

Input numbers range from 1 to 50 only, You are given these numbers in a column in a pandas dataframe. You need to create a new column in the SAME dataframe with column name <b>"Roman"</b> and list the corresponding Roman counterparts in that column. 

Roman numerals are represented by seven different symbols: I, V, X, and  L<br>
Symbol:Value<br>
I      :       1<br>
V       :      5<br>
X        :     10<br>
L         :    50<br>
For example, 2 is written as II in Roman numeral, just two one's added together. 12 is written as XII, which is simply X + II. The number 27 is written as XXVII, which is XX + V + II.<br>
Roman numerals are usually written largest to smallest from left to right. However, the numeral for four is not IIII. Instead, the number four is written as IV. Because the one is before the five we subtract it making four. The same principle applies to the number nine, which is written as IX. There are six instances where subtraction is used:<br>
I can be placed before V (5) and X (10) to make 4 and 9.<br>
X can be placed before L (50) to make 40.<br>
Given an integer in the range of 1 to 50 (both inclusive), convert it to a roman numeral.<br>
### NOTE: If you need a Roman mapping to any numeric value, you can ask us and we will provide it to you. You need to use df.apply to create the new Roman column. We have provided you with a function that you can use with df.apply


In [44]:
'''
This is an example of how the input will look like
'''
df_dict = {'Numeric':[4,12,11]}
inputDataFrame = pd.DataFrame(df_dict)
inputDataFrame


Numeric
0        4
1       12
2       11

In [45]:
'''
This is an example of how the expected output dataframe should look like.
'''
df_dict = {'Numeric':[4,12,11],'Roman':['IV','XII','XI']}
outputDataFrame = pd.DataFrame(df_dict)
outputDataFrame

Numeric Roman
0        4    IV
1       12   XII
2       11    XI

In [46]:
def question4(df):
    '''
    1 local test case : 15 points
    1 hidden test case : 25 points
    '''
    df = df.copy()
    df['Roman'] = df['Numeric'].apply(ntoRoman)
    return df

def ntoRoman(n):
    map = [
        (50, "L"), (40, "XL"), (10, "X"), (9, "IX"), (5, "V"), (4, "IV"), (1, "I")
    ]
    roman = ""
    for (value, symbol) in map:
        while n >= value:
            roman += symbol
            n -= value
    return roman

In [47]:
question4(inputDataFrame)

Numeric Roman
0        4    IV
1       12   XII
2       11    XI

### Submission Guidelines: 
#### 1. Save and run all the cells of this notebook.
#### 2. All the assignments in this course will have two types of test cases, local test cases and hidden test cases. You will be able to test your work on local test cases by running the cell  with - grader.check_all() or grader.check("question number")
#### 3. Once you are happy with the output of grader.check_all() and upload the notebook to gradescope
#### 4. You will be able to see the result of your work on hidden tests once the grades are released for a given assignment.

---

To double-check your work, the cell below will rerun all of the autograder tests.

In [ ]:
grader.check_all()